### ISSUE TITLE
starfit fails with old numpy

### ISSUE THREAD

**Issue by 2sn** [conradtchan/starfit#56]
```
import starfit
s = starfit.Single(
    filename = 'HE1327-2326.dat',
    db = 'znuc2012.S4.star.el.y.stardb.gz',
    combine = [[6, 7, 8]],
    z_max = 30,
    z_exclude = [3, 24, 30],
    z_lolim = [21, 29],
    upper_lim = True,
    cdf = True,
)
print(s)
Traceback (most recent call last):
  File "/Users/katmeletiou/.conda/envs/msc-project/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-73f2e78fc75b>", line 1, in <module>
    import starfit
  File "/Users/katmeletiou/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/222.4167.33/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/katmeletiou/.conda/envs/msc-project/lib/python3.8/site-packages/starfit/__init__.py", line 30, in <module>
    from .fit import Direct, Double, Single
  File "/Users/katmeletiou/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/222.4167.33/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/katmeletiou/.conda/envs/msc-project/lib/python3.8/site-packages/starfit/fit.py", line 14, in <module>
    from .solgen._solgen import comb, gen_slice
  File "/Users/katmeletiou/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/222.4167.33/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: numpy.core.multiarray failed to import
```
we likely need to require NumPy version at least 1.21, but maybe go for 1.23...

**Comment by 2sn** [comment]
fixed by #57
